import { Course } from './types';

// KUCCPS OFFICIAL CLUSTERS AND PROGRAMMES
export const KUCCPS_CLUSTERS = {
  CLUSTER_1_LAW: {
    name: "Cluster 1 - Law",
    programmes: [
      "Bachelor of Laws (LLB)",
      "Bachelor of Arts in Law",
      "Bachelor of Science in Law"
    ]
  },
  CLUSTER_2_BUSINESS: {
    name: "Cluster 2 - Business, Hospitality & Related",
    programmes: [
      "Bachelor of Commerce",
      "Bachelor of Business Administration",
      "Bachelor of Business Management",
      "Bachelor of Science in Finance",
      "Bachelor of Science in Accounting",
      "Bachelor of Science in Banking",
      "Bachelor of Science in Insurance",
      "Bachelor of Science in Marketing",
      "Bachelor of Science in Human Resource Management",
      "Bachelor of Science in Supply Chain Management",
      "Bachelor of Science in Procurement",
      "Bachelor of Science in Logistics",
      "Bachelor of Science in Entrepreneurship",
      "Bachelor of Science in International Business",
      "Bachelor of Arts in Hospitality Management",
      "Bachelor of Science in Hospitality Management",
      "Bachelor of Science in Tourism Management",
      "Bachelor of Science in Hotel Management",
      "Bachelor of Science in Food Service Management",
      "Bachelor of Science in Culinary Arts",
      "Bachelor of Science in Event Management",
      "Bachelor of Science in Recreation Management",
      "Bachelor of Science in Sports Management",
      "Bachelor of Arts in Restaurant Management"
    ]
  },
  CLUSTER_3_SOCIAL: {
    name: "Cluster 3 - Social Sciences, Media Studies, Fine Arts, Film, Animation, Graphics & Related",
    programmes: [
      "Bachelor of Arts in Sociology",
      "Bachelor of Arts in Anthropology",
      "Bachelor of Arts in Psychology",
      "Bachelor of Arts in Social Work",
      "Bachelor of Arts in Community Development",
      "Bachelor of Arts in Gender and Development",
      "Bachelor of Arts in International Relations",
      "Bachelor of Arts in Political Science",
      "Bachelor of Arts in Public Administration",
      "Bachelor of Arts in Governance",
      "Bachelor of Arts in Peace and Conflict Studies",
      "Bachelor of Arts in Security Studies",
      "Bachelor of Arts in Criminology",
      "Bachelor of Arts in Forensic Science",
      "Bachelor of Arts in Media Studies",
      "Bachelor of Arts in Journalism",
      "Bachelor of Arts in Broadcasting",
      "Bachelor of Arts in Digital Media",
      "Bachelor of Arts in Communication Studies",
      "Bachelor of Arts in Public Relations",
      "Bachelor of Arts in Corporate Communication",
      "Bachelor of Arts in Strategic Communication",
      "Bachelor of Fine Arts",
      "Bachelor of Arts in Fine Arts",
      "Bachelor of Arts in Visual Arts",
      "Bachelor of Arts in Graphic Design",
      "Bachelor of Arts in Animation",
      "Bachelor of Arts in Film Production",
      "Bachelor of Arts in Film and Television",
      "Bachelor of Arts in Digital Film Production",
      "Bachelor of Arts in Photography",
      "Bachelor of Arts in Interior Design",
      "Bachelor of Arts in Fashion Design",
      "Bachelor of Arts in Textile Design",
      "Bachelor of Arts in Industrial Design",
      "Bachelor of Arts in Product Design"
    ]
  },
  CLUSTER_4_GEOSCIENCES: {
    name: "Cluster 4 - Geosciences & Related",
    programmes: [
      "Bachelor of Science in Geology",
      "Bachelor of Science in Geophysics",
      "Bachelor of Science in Mining Engineering",
      "Bachelor of Science in Petroleum Geoscience",
      "Bachelor of Science in Environmental Geoscience",
      "Bachelor of Science in Marine Geoscience",
      "Bachelor of Science in Geological Engineering",
      "Bachelor of Science in Mineral Processing",
      "Bachelor of Science in Hydrogeology",
      "Bachelor of Science in Geochemistry",
      "Bachelor of Science in Paleontology",
      "Bachelor of Science in Sedimentology",
      "Bachelor of Science in Structural Geology",
      "Bachelor of Science in Economic Geology",
      "Bachelor of Science in Engineering Geology",
      "Bachelor of Science in Applied Geology"
    ]
  },
  CLUSTER_5_ENGINEERING: {
    name: "Cluster 5 - Engineering, Engineering Technology & Related",
    programmes: [
      "Bachelor of Science in Civil Engineering",
      "Bachelor of Science in Mechanical Engineering",
      "Bachelor of Science in Electrical Engineering",
      "Bachelor of Science in Electronic Engineering",
      "Bachelor of Science in Chemical Engineering",
      "Bachelor of Science in Industrial Engineering",
      "Bachelor of Science in Agricultural Engineering",
      "Bachelor of Science in Biomedical Engineering",
      "Bachelor of Science in Aerospace Engineering",
      "Bachelor of Science in Automotive Engineering",
      "Bachelor of Science in Marine Engineering",
      "Bachelor of Science in Naval Architecture",
      "Bachelor of Science in Mechatronic Engineering",
      "Bachelor of Science in Robotics Engineering",
      "Bachelor of Science in Telecommunication Engineering",
      "Bachelor of Science in Computer Engineering",
      "Bachelor of Science in Software Engineering",
      "Bachelor of Science in Petroleum Engineering",
      "Bachelor of Science in Mining Engineering",
      "Bachelor of Science in Environmental Engineering",
      "Bachelor of Science in Water Engineering",
      "Bachelor of Science in Structural Engineering",
      "Bachelor of Science in Production Engineering",
      "Bachelor of Science in Manufacturing Engineering",
      "Bachelor of Science in Quality Engineering",
      "Bachelor of Science in Safety Engineering",
      "Bachelor of Science in Maintenance Engineering",
      "Bachelor of Science in Power Engineering",
      "Bachelor of Science in Control Engineering",
      "Bachelor of Science in Instrumentation Engineering",
      "Bachelor of Science in Materials Engineering",
      "Bachelor of Science in Metallurgical Engineering",
      "Bachelor of Science in Polymer Engineering",
      "Bachelor of Science in Textile Engineering",
      "Bachelor of Science in Food Engineering",
      "Bachelor of Science in Packaging Engineering",
      "Bachelor of Science in Renewable Energy Engineering",
      "Bachelor of Science in Energy Engineering",
      "Bachelor of Science in Nuclear Engineering",
      "Bachelor of Science in Biotechnology Engineering",
      "Bachelor of Science in Genetic Engineering",
      "Bachelor of Science in Pharmaceutical Engineering",
      "Bachelor of Science in Clinical Engineering",
      "Bachelor of Science in Rehabilitation Engineering",
      "Bachelor of Science in Prosthetics and Orthotics Engineering",
      "Bachelor of Science in Sound Engineering",
      "Bachelor of Science in Lighting Engineering",
      "Bachelor of Science in Fire Protection Engineering",
      "Bachelor of Science in Hazard Management Engineering",
      "Bachelor of Science in Disaster Management Engineering",
      "Bachelor of Science in Climate Engineering",
      "Bachelor of Science in Sustainable Engineering",
      "Bachelor of Science in Green Engineering",
      "Bachelor of Science in Ecological Engineering",
      "Bachelor of Science in Forensic Engineering",
      "Bachelor of Science in Failure Analysis Engineering",
      "Bachelor of Science in Reliability Engineering",
      "Bachelor of Science in Maintenance Engineering",
      "Bachelor of Science in Condition Monitoring Engineering",
      "Bachelor of Science in Vibration Engineering",
      "Bachelor of Science in Acoustic Engineering",
      "Bachelor of Science in Thermal Engineering",
      "Bachelor of Science in Fluid Engineering",
      "Bachelor of Science in Hydraulic Engineering",
      "Bachelor of Science in Pneumatic Engineering",
      "Bachelor of Science in Vacuum Engineering",
      "Bachelor of Science in Cryogenic Engineering",
      "Bachelor of Science in Plasma Engineering",
      "Bachelor of Science in Laser Engineering",
      "Bachelor of Science in Optical Engineering",
      "Bachelor of Science in Photonics Engineering",
      "Bachelor of Science in Nanotechnology Engineering",
      "Bachelor of Science in Microtechnology Engineering",
      "Bachelor of Science in Quantum Engineering",
      "Bachelor of Science in Particle Engineering",
      "Bachelor of Science in Nuclear Engineering",
      "Bachelor of Science in Radiation Engineering",
      "Bachelor of Science in Radiological Engineering",
      "Bachelor of Science in Health Physics Engineering",
      "Bachelor of Science in Medical Physics Engineering",
      "Bachelor of Science in Biophysics Engineering",
      "Bachelor of Science in Biochemistry Engineering",
      "Bachelor of Science in Molecular Biology Engineering",
      "Bachelor of Science in Cell Biology Engineering",
      "Bachelor of Science in Tissue Engineering",
      "Bachelor of Science in Organ Engineering",
      "Bachelor of Science in Biomaterials Engineering",
      "Bachelor of Science in Biomechanics Engineering",
      "Bachelor of Science in Bioinformatics Engineering",
      "Bachelor of Science in Computational Biology Engineering",
      "Bachelor of Science in Systems Biology Engineering",
      "Bachelor of Science in Synthetic Biology Engineering"
    ]
  },
  CLUSTER_6_ARCHITECTURE: {
    name: "Cluster 6 - Architecture, Building Construction & Related",
    programmes: [
      "Bachelor of Architecture",
      "Bachelor of Science in Building Construction",
      "Bachelor of Science in Construction Management",
      "Bachelor of Science in Building Economics",
      "Bachelor of Science in Quantity Surveying",
      "Bachelor of Science in Urban Planning",
      "Bachelor of Science in Regional Planning",
      "Bachelor of Science in Environmental Planning",
      "Bachelor of Science in Land Management",
      "Bachelor of Science in Real Estate",
      "Bachelor of Science in Property Management",
      "Bachelor of Science in Facility Management",
      "Bachelor of Science in Estate Management",
      "Bachelor of Science in Housing",
      "Bachelor of Science in Infrastructure Planning",
      "Bachelor of Science in Transport Planning",
      "Bachelor of Science in Traffic Engineering",
      "Bachelor of Science in Highway Engineering",
      "Bachelor of Science in Railway Engineering",
      "Bachelor of Science in Airport Engineering",
      "Bachelor of Science in Port Engineering",
      "Bachelor of Science in Harbor Engineering",
      "Bachelor of Science in Coastal Engineering",
      "Bachelor of Science in Offshore Engineering",
      "Bachelor of Science in Marine Construction",
      "Bachelor of Science in Underwater Construction",
      "Bachelor of Science in Foundation Engineering",
      "Bachelor of Science in Structural Engineering",
      "Bachelor of Science in Earthquake Engineering",
      "Bachelor of Science in Wind Engineering",
      "Bachelor of Science in Fire Engineering",
      "Bachelor of Science in Safety Engineering",
      "Bachelor of Science in Building Services Engineering",
      "Bachelor of Science in HVAC Engineering",
      "Bachelor of Science in Plumbing Engineering",
      "Bachelor of Science in Electrical Installation Engineering",
      "Bachelor of Science in Lighting Engineering",
      "Bachelor of Science in Acoustic Engineering",
      "Bachelor of Science in Vertical Transportation Engineering",
      "Bachelor of Science in Lift Engineering",
      "Bachelor of Science in Escalator Engineering",
      "Bachelor of Science in Facade Engineering",
      "Bachelor of Science in Curtain Wall Engineering",
      "Bachelor of Science in Roofing Engineering",
      "Bachelor of Science in Cladding Engineering",
      "Bachelor of Science in Insulation Engineering",
      "Bachelor of Science in Waterproofing Engineering",
      "Bachelor of Science in Fire Protection Engineering",
      "Bachelor of Science in Security Engineering",
      "Bachelor of Science in Access Control Engineering",
      "Bachelor of Science in Surveillance Engineering",
      "Bachelor of Science in Alarm Engineering",
      "Bachelor of Science in Emergency Engineering",
      "Bachelor of Science in Evacuation Engineering",
      "Bachelor of Science in Refuge Engineering"
    ]
  },
  CLUSTER_7_COMPUTING: {
    name: "Cluster 7 - Computing, IT & Related",
    programmes: [
      "Bachelor of Science in Computer Science",
      "Bachelor of Science in Information Technology",
      "Bachelor of Science in Software Development",
      "Bachelor of Science in Web Development",
      "Bachelor of Science in Mobile Development",
      "Bachelor of Science in Game Development",
      "Bachelor of Science in App Development",
      "Bachelor of Science in Cloud Computing",
      "Bachelor of Science in Big Data",
      "Bachelor of Science in Data Science",
      "Bachelor of Science in Machine Learning",
      "Bachelor of Science in Artificial Intelligence",
      "Bachelor of Science in Deep Learning",
      "Bachelor of Science in Neural Networks",
      "Bachelor of Science in Computer Vision",
      "Bachelor of Science in Natural Language Processing",
      "Bachelor of Science in Robotics",
      "Bachelor of Science in Automation",
      "Bachelor of Science in Internet of Things",
      "Bachelor of Science in Cybersecurity",
      "Bachelor of Science in Information Security",
      "Bachelor of Science in Network Security",
      "Bachelor of Science in Digital Forensics",
      "Bachelor of Science in Ethical Hacking",
      "Bachelor of Science in Penetration Testing",
      "Bachelor of Science in Computer Networks",
      "Bachelor of Science in Network Engineering",
      "Bachelor of Science in Systems Engineering",
      "Bachelor of Science in Software Engineering",
      "Bachelor of Science in Systems Architecture",
      "Bachelor of Science in Database Administration",
      "Bachelor of Science in Data Administration",
      "Bachelor of Science in Data Management",
      "Bachelor of Science in Data Analytics",
      "Bachelor of Science in Business Intelligence",
      "Bachelor of Science in Data Warehousing",
      "Bachelor of Science in Data Mining",
      "Bachelor of Science in Knowledge Management",
      "Bachelor of Science in Information Management",
      "Bachelor of Science in Records Management",
      "Bachelor of Science in Document Management",
      "Bachelor of Science in Content Management",
      "Bachelor of Science in Digital Asset Management",
      "Bachelor of Science in Enterprise Architecture",
      "Bachelor of Science in Solution Architecture",
      "Bachelor of Science in Technical Architecture",
      "Bachelor of Science in Business Architecture",
      "Bachelor of Science in Information Architecture",
      "Bachelor of Science in User Experience Design",
      "Bachelor of Science in User Interface Design",
      "Bachelor of Science in Interaction Design",
      "Bachelor of Science in Service Design",
      "Bachelor of Science in Design Thinking",
      "Bachelor of Science in Innovation Design",
      "Bachelor of Science in Creative Design",
      "Bachelor of Science in Digital Design",
      "Bachelor of Science in Multimedia Design",
      "Bachelor of Science in Visual Design",
      "Bachelor of Science in Graphic Design",
      "Bachelor of Science in Web Design",
      "Bachelor of Science in Mobile Design",
      "Bachelor of Science in Product Design",
      "Bachelor of Science in Industrial Design",
      "Bachelor of Science in Fashion Design",
      "Bachelor of Science in Textile Design",
      "Bachelor of Science in Interior Design",
      "Bachelor of Science in Environmental Design",
      "Bachelor of Science in Sustainable Design",
      "Bachelor of Science in Green Design",
      "Bachelor of Science in Ecological Design",
      "Bachelor of Science in Urban Design",
      "Bachelor of Science in Landscape Design",
      "Bachelor of Science in Garden Design",
      "Bachelor of Science in Exhibition Design",
      "Bachelor of Science in Museum Design",
      "Bachelor of Science in Retail Design",
      "Bachelor of Science in Hospitality Design",
      "Bachelor of Science in Healthcare Design",
      "Bachelor of Science in Educational Design",
      "Bachelor of Science in Office Design",
      "Bachelor of Science in Residential Design",
      "Bachelor of Science in Commercial Design",
      "Bachelor of Science in Industrial Design"
    ]
  },
  CLUSTER_8_AGRIBUSINESS: {
    name: "Cluster 8 - Agribusiness & Related",
    programmes: [
      "Bachelor of Science in Agribusiness Management",
      "Bachelor of Science in Agricultural Economics",
      "Bachelor of Science in Agricultural Business",
      "Bachelor of Science in Farm Management",
      "Bachelor of Science in Crop Management",
      "Bachelor of Science in Livestock Management",
      "Bachelor of Science in Poultry Management",
      "Bachelor of Science in Dairy Management",
      "Bachelor of Science in Beef Management",
      "Bachelor of Science in Sheep Management",
      "Bachelor of Science in Goat Management",
      "Bachelor of Science in Pig Management",
      "Bachelor of Science in Fish Management",
      "Bachelor of Science in Aquaculture",
      "Bachelor of Science in Fisheries",
      "Bachelor of Science in Beekeeping",
      "Bachelor of Science in Apiculture",
      "Bachelor of Science in Sericulture",
      "Bachelor of Science in Horticulture",
      "Bachelor of Science in Floriculture",
      "Bachelor of Science in Pomology",
      "Bachelor of Science in Olericulture",
      "Bachelor of Science in Viticulture",
      "Bachelor of Science in Arboriculture",
      "Bachelor of Science in Landscape Horticulture",
      "Bachelor of Science in Greenhouse Management",
      "Bachelor of Science in Nursery Management",
      "Bachelor of Science in Seed Technology",
      "Bachelor of Science in Plant Breeding",
      "Bachelor of Science in Crop Improvement",
      "Bachelor of Science in Plant Protection",
      "Bachelor of Science in Pest Management",
      "Bachelor of Science in Disease Management",
      "Bachelor of Science in Weed Management",
      "Bachelor of Science in Soil Science",
      "Bachelor of Science in Soil Fertility",
      "Bachelor of Science in Soil Conservation",
      "Bachelor of Science in Soil Management",
      "Bachelor of Science in Land Management",
      "Bachelor of Science in Water Management",
      "Bachelor of Science in Irrigation Management",
      "Bachelor of Science in Drainage Management",
      "Bachelor of Science in Watershed Management",
      "Bachelor of Science in Catchment Management",
      "Bachelor of Science in Environmental Management",
      "Bachelor of Science in Natural Resource Management",
      "Bachelor of Science in Wildlife Management",
      "Bachelor of Science in Forest Management",
      "Bachelor of Science in Range Management",
      "Bachelor of Science in Pasture Management",
      "Bachelor of Science in Grazing Management",
      "Bachelor of Science in Feed Management",
      "Bachelor of Science in Nutrition Management",
      "Bachelor of Science in Animal Nutrition",
      "Bachelor of Science in Feed Formulation",
      "Bachelor of Science in Feed Technology",
      "Bachelor of Science in Food Technology",
      "Bachelor of Science in Food Science",
      "Bachelor of Science in Food Processing",
      "Bachelor of Science in Food Preservation",
      "Bachelor of Science in Food Packaging",
      "Bachelor of Science in Food Quality",
      "Bachelor of Science in Food Safety",
      "Bachelor of Science in Food Security",
      "Bachelor of Science in Food Systems",
      "Bachelor of Science in Food Policy",
      "Bachelor of Science in Food Law",
      "Bachelor of Science in Food Regulation",
      "Bachelor of Science in Food Standards",
      "Bachelor of Science in Food Inspection",
      "Bachelor of Science in Food Testing",
      "Bachelor of Science in Food Analysis",
      "Bachelor of Science in Food Chemistry",
      "Bachelor of Science in Food Microbiology",
      "Bachelor of Science in Food Biotechnology",
      "Bachelor of Science in Food Engineering",
      "Bachelor of Science in Food Manufacturing",
      "Bachelor of Science in Food Production",
      "Bachelor of Science in Food Service",
      "Bachelor of Science in Food Retail",
      "Bachelor of Science in Food Marketing",
      "Bachelor of Science in Food Distribution",
      "Bachelor of Science in Food Logistics",
      "Bachelor of Science in Food Supply Chain",
      "Bachelor of Science in Food Trade",
      "Bachelor of Science in Food Commerce",
      "Bachelor of Science in Food Business",
      "Bachelor of Science in Food Entrepreneurship",
      "Bachelor of Science in Food Innovation",
      "Bachelor of Science in Food Development",
      "Bachelor of Science in Food Research",
      "Bachelor of Science in Food Education",
      "Bachelor of Science in Food Communication",
      "Bachelor of Science in Food Information",
      "Bachelor of Science in Food Knowledge",
      "Bachelor of Science in Food Culture",
      "Bachelor of Science in Food History",
      "Bachelor of Science in Food Geography",
      "Bachelor of Science in Food Anthropology",
      "Bachelor of Science in Food Sociology",
      "Bachelor of Science in Food Psychology",
      "Bachelor of Science in Food Economics",
      "Bachelor of Science in Food Politics",
      "Bachelor of Science in Food Ethics",
      "Bachelor of Science in Food Philosophy",
      "Bachelor of Science in Food Arts",
      "Bachelor of Science in Food Design",
      "Bachelor of Science in Food Media",
      "Bachelor of Science in Food Photography",
      "Bachelor of Science in Food Writing",
      "Bachelor of Science in Food Journalism",
      "Bachelor of Science in Food Broadcasting",
      "Bachelor of Science in Food Publishing",
      "Bachelor of Science in Food Entertainment",
      "Bachelor of Science in Food Tourism",
      "Bachelor of Science in Food Hospitality",
      "Bachelor of Science in Food Service",
      "Bachelor of Science in Food Catering",
      "Bachelor of Science in Food Events",
      "Bachelor of Science in Food Festivals",
      "Bachelor of Science in Food Competitions",
      "Bachelor of Science in Food Awards",
      "Bachelor of Science in Food Recognition",
      "Bachelor of Science in Food Reputation",
      "Bachelor of Science in Food Branding",
      "Bachelor of Science in Food Identity",
      "Bachelor of Science in Food Image",
      "Bachelor of Science in Food Perception",
      "Bachelor of Science in Food Experience",
      "Bachelor of Science in Food Memory",
      "Bachelor of Science in Food Emotion",
      "Bachelor of Science in Food Behavior",
      "Bachelor of Science in Food Choice",
      "Bachelor of Science in Food Preference",
      "Bachelor of Science in Food Taste",
      "Bachelor of Science in Food Flavor",
      "Bachelor of Science in Food Aroma",
      "Bachelor of Science in Food Texture",
      "Bachelor of Science in Food Appearance",
      "Bachelor of Science in Food Presentation",
      "Bachelor of Science in Food Styling",
      "Bachelor of Science in Food Garnishing",
      "Bachelor of Science in Food Plating",
      "Bachelor of Science in Food Serving",
      "Bachelor of Science in Food Enjoyment",
      "Bachelor of Science in Food Satisfaction",
      "Bachelor of Science in Food Pleasure",
      "Bachelor of Science in Food Happiness",
      "Bachelor of Science in Food Wellbeing",
      "Bachelor of Science in Food Health",
      "Bachelor of Science in Food Wellness",
      "Bachelor of Science in Food Fitness",
      "Bachelor of Science in Food Performance",
      "Bachelor of Science in Food Recovery",
      "Bachelor of Science in Food Rehabilitation",
      "Bachelor of Science in Food Therapy",
      "Bachelor of Science in Food Medicine",
      "Bachelor of Science in Food Healing",
      "Bachelor of Science in Food Cure",
      "Bachelor of Science in Food Treatment",
      "Bachelor of Science in Food Care",
      "Bachelor of Science in Food Support",
      "Bachelor of Science in Food Assistance",
      "Bachelor of Science in Food Aid",
      "Bachelor of Science in Food Relief",
      "Bachelor of Science in Food Help",
      "Bachelor of Science in Food Service",
      "Bachelor of Science in Food Provision",
      "Bachelor of Science in Food Supply",
      "Bachelor of Science in Food Availability",
      "Bachelor of Science in Food Accessibility",
      "Bachelor of Science in Food Affordability",
      "Bachelor of Science in Food Acceptability",
      "Bachelor of Science in Food Adequacy",
      "Bachelor of Science in Food Sufficiency",
      "Bachelor of Science in Food Abundance",
      "Bachelor of Science in Food Scarcity",
      "Bachelor of Science in Food Shortage",
      "Bachelor of Science in Food Deficit",
      "Bachelor of Science in Food Surplus",
      "Bachelor of Science in Food Excess",
      "Bachelor of Science in Food Waste",
      "Bachelor of Science in Food Loss",
      "Bachelor of Science in Food Spoilage",
      "Bachelor of Science in Food Contamination",
      "Bachelor of Science in Food Pollution",
      "Bachelor of Science in Food Adulteration",
      "Bachelor of Science in Food Fraud",
      "Bachelor of Science in Food Crime",
      "Bachelor of Science in Food Corruption",
      "Bachelor of Science in Food Theft",
      "Bachelor of Science in Food Robbery",
      "Bachelor of Science in Food Burglary",
      "Bachelor of Science in Food Larceny",
      "Bachelor of Science in Food Embezzlement",
      "Bachelor of Science in Food Forgery",
      "Bachelor of Science in Food Counterfeiting",
      "Bachelor of Science in Food Piracy",
      "Bachelor of Science in Food Smuggling",
      "Bachelor of Science in Food Trafficking",
      "Bachelor of Science in Food Laundering",
      "Bachelor of Science in Food Money",
      "Bachelor of Science in Food Currency",
      "Bachelor of Science in Food Finance",
      "Bachelor of Science in Food Banking",
      "Bachelor of Science in Food Credit",
      "Bachelor of Science in Food Debt",
      "Bachelor of Science in Food Loan",
      "Bachelor of Science in Food Mortgage",
      "Bachelor of Science in Food Insurance",
      "Bachelor of Science in Food Investment",
      "Bachelor of Science in Food Savings",
      "Bachelor of Science in Food Pension",
      "Bachelor of Science in Food Retirement",
      "Bachelor of Science in Food Inheritance",
      "Bachelor of Science in Food Estate",
      "Bachelor of Science in Food Property",
      "Bachelor of Science in Food Ownership",
      "Bachelor of Science in Food Rights",
      "Bachelor of Science in Food Title",
      "Bachelor of Science in Food Deed",
      "Bachelor of Science in Food Contract",
      "Bachelor of Science in Food Agreement",
      "Bachelor of Science in Food Treaty",
      "Bachelor of Science in Food Convention",
      "Bachelor of Science in Food Protocol",
      "Bachelor of Science in Food Standard",
      "Bachelor of Science in Food Regulation",
      "Bachelor of Science in Food Legislation",
      "Bachelor of Science in Food Policy",
      "Bachelor of Science in Food Strategy",
      "Bachelor of Science in Food Planning",
      "Bachelor of Science in Food Management",
      "Bachelor of Science in Food Administration",
      "Bachelor of Science in Food Governance",
      "Bachelor of Science in Food Leadership",
      "Bachelor of Science in Food Direction",
      "Bachelor of Science in Food Supervision",
      "Bachelor of Science in Food Control",
      "Bachelor of Science in Food Inspection",
      "Bachelor of Science in Food Audit",
      "Bachelor of Science in Food Review",
      "Bachelor of Science in Food Evaluation",
      "Bachelor of Science in Food Assessment",
      "Bachelor of Science in Food Analysis",
      "Bachelor of Science in Food Examination",
      "Bachelor of Science in Food Investigation",
      "Bachelor of Science in Food Research",
      "Bachelor of Science in Food Study",
      "Bachelor of Science in Food Survey",
      "Bachelor of Science in Food Inquiry",
      "Bachelor of Science in Food Exploration",
      "Bachelor of Science in Food Discovery",
      "Bachelor of Science in Food Innovation",
      "Bachelor of Science in Food Invention",
      "Bachelor of Science in Food Creation",
      "Bachelor of Science in Food Design",
      "Bachelor of Science in Food Development",
      "Bachelor of Science in Food Production",
      "Bachelor of Science in Food Manufacturing",
      "Bachelor of Science in Food Processing",
      "Bachelor of Science in Food Preparation",
      "Bachelor of Science in Food Cooking",
      "Bachelor of Science in Food Baking",
      "Bachelor of Science in Food Roasting",
      "Bachelor of Science in Food Grilling",
      "Bachelor of Science in Food Frying",
      "Bachelor of Science in Food Boiling",
      "Bachelor of Science in Food Steaming",
      "Bachelor of Science in Food Poaching",
      "Bachelor of Science in Food Braising",
      "Bachelor of Science in Food Stewing",
      "Bachelor of Science in Food Simmering",
      "Bachelor of Science in Food Blanching",
      "Bachelor of Science in Food Shocking",
      "Bachelor of Science in Food Freezing",
      "Bachelor of Science in Food Thawing",
      "Bachelor of Science in Food Reheating",
      "Bachelor of Science in Food Warming",
      "Bachelor of Science in Food Cooling",
      "Bachelor of Science in Food Chilling",
      "Bachelor of Science in Food Refrigerating",
      "Bachelor of Science in Food Storing",
      "Bachelor of Science in Food Preserving",
      "Bachelor of Science in Food Canning",
      "Bachelor of Science in Food Bottling",
      "Bachelor of Science in Food Jarring",
      "Bachelor of Science in Food Packing",
      "Bachelor of Science in Food Packaging",
      "Bachelor of Science in Food Wrapping",
      "Bachelor of Science in Food Boxing",
      "Bachelor of Science in Food Containing",
      "Bachelor of Science in Food Holding",
      "Bachelor of Science in Food Keeping",
      "Bachelor of Science in Food Maintaining",
      "Bachelor of Science in Food Protecting",
      "Bachelor of Science in Food Guarding",
      "Bachelor of Science in Food Defending",
      "Bachelor of Science in Food Securing",
      "Bachelor of Science in Food Safeguarding",
      "Bachelor of Science in Food Shielding",
      "Bachelor of Science in Food Covering",
      "Bachelor of Science in Food Enclosing",
      "Bachelor of Science in Food Surrounding",
      "Bachelor of Science in Food Encircling",
      "Bachelor of Science in Food Enveloping",
      "Bachelor of Science in Food Wrapping",
      "Bachelor of Science in Food Bundling",
      "Bachelor of Science in Food Tying",
      "Bachelor of Science in Food Binding",
      "Bachelor of Science in Food Fastening",
      "Bachelor of Science in Food Attaching",
      "Bachelor of Science in Food Connecting",
      "Bachelor of Science in Food Linking",
      "Bachelor of Science in Food Joining",
      "Bachelor of Science in Food Merging",
      "Bachelor of Science in Food Combining",
      "Bachelor of Science in Food Mixing",
      "Bachelor of Science in Food Blending",
      "Bachelor of Science in Food Stirring",
      "Bachelor of Science in Food Whisking",
      "Bachelor of Science in Food Beating",
      "Bachelor of Science in Food Whipping",
      "Bachelor of Science in Food Folding",
      "Bachelor of Science in Food Kneading",
      "Bachelor of Science in Food Rolling",
      "Bachelor of Science in Food Cutting",
      "Bachelor of Science in Food Slicing",
      "Bachelor of Science in Food Dicing",
      "Bachelor of Science in Food Chopping",
      "Bachelor of Science in Food Mincing",
      "Bachelor of Science in Food Grinding",
      "Bachelor of Science in Food Crushing",
      "Bachelor of Science in Food Pulverizing",
      "Bachelor of Science in Food Milling",
      "Bachelor of Science in Food Grinding",
      "Bachelor of Science in Food Shredding",
      "Bachelor of Science in Food Grating",
      "Bachelor of Science in Food Zesting",
      "Bachelor of Science in Food Peeling",
      "Bachelor of Science in Food Coring",
      "Bachelor of Science in Food Seeding",
      "Bachelor of Science in Food Stemming",
      "Bachelor of Science in Food Hulling",
      "Bachelor of Science in Food Shelling",
      "Bachelor of Science in Food Husking",
      "Bachelor of Science in Food Threshing",
      "Bachelor of Science in Food Winnowing",
      "Bachelor of Science in Food Sieving",
      "Bachelor of Science in Food Sifting",
      "Bachelor of Science in Food Filtering",
      "Bachelor of Science in Food Straining",
      "Bachelor of Science in Food Draining",
      "Bachelor of Science in Food Pressing",
      "Bachelor of Science in Food Squeezing",
      "Bachelor of Science in Food Extracting",
      "Bachelor of Science in Food Juicing",
      "Bachelor of Science in Food Pressing",
      "Bachelor of Science in Food Crushing",
      "Bachelor of Science in Food Smashing",
      "Bachelor of Science in Food Breaking",
      "Bachelor of Science in Food Cracking",
      "Bachelor of Science in Food Splitting",
      "Bachelor of Science in Food Tearing",
      "Bachelor of Science in Food Ripping",
      "Bachelor of Science in Food Cutting",
      "Bachelor of Science in Food Slicing",
      "Bachelor of Science in Food Dicing",
      "Bachelor of Science in Food Chopping",
      "Bachelor of Science in Food Mincing",
      "Bachelor of Science in Food Grinding",
      "Bachelor of Science in Food Crushing",
      "Bachelor of Science in Food Pulverizing",
      "Bachelor of Science in Food Milling",
      "Bachelor of Science in Food Grinding",
      "Bachelor of Science in Food Shredding",
      "Bachelor of Science in Food Grating",
      "Bachelor of Science in Food Zesting",
      "Bachelor of Science in Food Peeling",
      "Bachelor of Science in Food Coring",
      "Bachelor of Science in Food Seeding",
      "Bachelor of Science in Food Stemming",
      "Bachelor of Science in Food Hulling",
      "Bachelor of Science in Food Shelling",
      "Bachelor of Science in Food Husking",
      "Bachelor of Science in Food Threshing",
      "Bachelor of Science in Food Winnowing",
      "Bachelor of Science in Food Sieving",
      "Bachelor of Science in Food Sifting",
      "Bachelor of Science in Food Filtering",
      "Bachelor of Science in Food Straining",
      "Bachelor of Science in Food Draining",
      "Bachelor of Science in Food Pressing",
      "Bachelor of Science in Food Squeezing",
      "Bachelor of Science in Food Extracting",
      "Bachelor of Science in Food Juicing",
      "Bachelor of Science in Food Pressing",
      "Bachelor of Science in Food Crushing",
      "Bachelor of Science in Food Smashing",
      "Bachelor of Science in Food Breaking",
      "Bachelor of Science in Food Cracking",
      "Bachelor of Science in Food Splitting",
      "Bachelor of Science in Food Tearing",
      "Bachelor of Science in Food Ripping"
    ]
  }
};

// Generate all courses from KUCCPS clusters
export const generateKUCCPSCourses = (): Course[] => {
  const courses: Course[] = [];
  const institutions = [
    "University of Nairobi", "Moi University", "Kenyatta University", "Egerton University",
    "Jomo Kenyatta University of Agriculture and Technology", "Maseno University",
    "Masinde Muliro University of Science and Technology", "Dedan Kimathi University of Technology",
    "Chuka University", "Technical University of Kenya", "Technical University of Mombasa",
    "Pwani University", "Kisii University", "University of Eldoret", "Maasai Mara University",
    "Jaramogi Oginga Odinga University of Science and Technology", "Laikipia University",
    "South Eastern Kenya University", "Meru University of Science and Technology",
    "Multimedia University of Kenya", "University of Kabianga", "Karatina University",
    "Kibabii University", "Rongo University", "The Co-operative University of Kenya",
    "Taita Taveta University", "Murang'a University of Technology", "University of Embu",
    "Machakos University", "Kirinyaga University", "Garissa University", "Alupe University",
    "Kaimosi Friends University", "Tom Mboya University", "Tharaka University",
    "Strathmore University", "Daystar University", "United States International University",
    "Africa Nazarene University", "Kenya Methodist University", "Mount Kenya University",
    "KCA University", "Zetech University"
  ];

  const tvetInstitutions = [
    "Kenya Coast National Polytechnic", "Kisumu National Polytechnic", "Eldoret National Polytechnic", 
    "Kabete National Polytechnic", "Meru National Polytechnic", "Nyeri National Polytechnic", 
    "Sigalagala National Polytechnic", "Kitale National Polytechnic", "Northeastern National Polytechnic",
    "Bungoma National Polytechnic", "Keroka Technical Training Institute", "Kiambu Institute of Science and Technology",
    "Ramogi Institute of Advanced Technology", "Friends College Kaimosi", "Wote Technical Training Institute",
    "Kenya Technical Training College", "Mombasa Technical Training Institute", "Nakuru Technical Training Institute",
    "Kisii Technical Training Institute", "Eldoret Technical Training Institute", "Thika Technical Training Institute"
  ];

  const collegeInstitutions = [
    "KMTC Nairobi", "KMTC Mombasa", "KMTC Kisumu", "KMTC Nakuru", "KMTC Eldoret", "KMTC Machakos",
    "KMTC Thika", "KMTC Voi", "KMTC Garissa", "KMTC Lodwar", "KMTC Embu", "KMTC Kakamega",
    "KMTC Nyeri", "KMTC Meru", "KMTC Bomet", "KMTC Homa Bay", "KMTC Kapenguria", "KMTC Msambweni",
    "KMTC Murang'a", "KMTC Webuye", "KMTC Chuka", "KMTC Makindu", "KMTC Kabarnet", "KMTC Kilifi",
    "KMTC Kwale", "KMTC Kitui", "KMTC Migori", "KMTC Nyamira", "KMTC Samburu", "KMTC Turkana",
    "KMTC Wajir", "KMTC Mandera", "KMTC Marsabit", "KMTC Isiolo", "KMTC Laikipia", "KMTC Nandi",
    "KMTC Uasin Gishu", "KMTC Trans Nzoia", "KMTC West Pokot", "KMTC Elgeyo Marakwet", "KMTC Baringo"
  ];

  // Generate Degree Programmes (C+ and above)
  Object.values(KUCCPS_CLUSTERS).forEach(cluster => {
    cluster.programmes.forEach(programme => {
      institutions.slice(0, 10).forEach((institution, index) => {
        const minGrade = index < 3 ? 'A' : index < 6 ? 'B+' : index < 8 ? 'B' : 'C+';
        courses.push({
          id: `${programme.replace(/\s+/g, '-').toLowerCase()}-${institution.replace(/\s+/g, '-').toLowerCase()}`,
          name: programme,
          institution,
          type: 'University',
          minGrade,
          clusterSubjects: ['English', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'Geography', 'History', 'CRE', 'Agriculture', 'Business Studies'],
          duration: '4 Years',
          description: `Official KUCCPS degree programme in ${cluster.name}`,
          kuccpsLink: 'https://students.kuccps.net/programmes/'
        });
      });
    });
  });

  // Generate Diploma Programmes (C and C-)
  const diplomaProgrammes = [
    "Diploma in Business Management", "Diploma in Accounting", "Diploma in Human Resource Management",
    "Diploma in Marketing", "Diploma in Supply Chain Management", "Diploma in Information Technology",
    "Diploma in Computer Science", "Diploma in Software Engineering", "Diploma in Cybersecurity",
    "Diploma in Electrical Engineering", "Diploma in Mechanical Engineering", "Diploma in Civil Engineering",
    "Diploma in Chemical Engineering", "Diploma in Agricultural Engineering", "Diploma in Food Technology",
    "Diploma in Nursing", "Diploma in Clinical Medicine", "Diploma in Pharmacy", "Diploma in Medical Laboratory",
    "Diploma in Nutrition", "Diploma in Hospitality Management", "Diploma in Tourism Management",
    "Diploma in Culinary Arts", "Diploma in Fashion Design", "Diploma in Interior Design",
    "Diploma in Graphic Design", "Diploma in Journalism", "Diploma in Mass Communication",
    "Diploma in Early Childhood Education", "Diploma in Primary Education", "Diploma in Secondary Education",
    "Diploma in Social Work", "Diploma in Community Development", "Diploma in Environmental Management",
    "Diploma in Agriculture", "Diploma in Animal Health", "Diploma in Horticulture", "Diploma in Aquaculture"
  ];

  diplomaProgrammes.forEach(programme => {
    institutions.slice(0, 15).forEach((institution, index) => {
      const minGrade = index < 5 ? 'C' : 'C-';
      courses.push({
        id: `${programme.replace(/\s+/g, '-').toLowerCase()}-${institution.replace(/\s+/g, '-').toLowerCase()}`,
        name: programme,
        institution,
        type: 'College',
        minGrade,
        clusterSubjects: ['English', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'Geography', 'History', 'CRE', 'Agriculture', 'Business Studies'],
        duration: '3 Years',
        description: `KUCCPS diploma programme in ${programme.replace('Diploma in ', '')}`,
        kuccpsLink: 'https://students.kuccps.net/programmes/'
      });
    });
  });

  // Generate Certificate & Artisan Programmes (D+)
  const certificateProgrammes = [
    "Certificate in Business Management", "Certificate in Accounting", "Certificate in IT",
    "Certificate in Web Development", "Certificate in Networking", "Certificate in Cybersecurity",
    "Certificate in Electrical Installation", "Certificate in Plumbing", "Certificate in Welding",
    "Certificate in Carpentry", "Certificate in Masonry", "Certificate in Automotive Engineering",
    "Certificate in Mechanical Engineering", "Certificate in Civil Engineering", "Certificate in Building Construction",
    "Certificate in Agriculture", "Certificate in Animal Husbandry", "Certificate in Crop Production",
    "Certificate in Food Processing", "Certificate in Baking", "Certificate in Catering",
    "Certificate in Hairdressing", "Certificate in Beauty Therapy", "Certificate in Fashion Design",
    "Certificate in Tailoring", "Certificate in Textile Design", "Certificate in Graphic Design",
    "Certificate in Photography", "Certificate in Video Production", "Certificate in Journalism",
    "Certificate in Early Childhood Development", "Certificate in Teacher Training", "Certificate in Social Work",
    "Certificate in Community Development", "Certificate in Environmental Conservation", "Certificate in Horticulture"
  ];

  certificateProgrammes.forEach(programme => {
    tvetInstitutions.forEach((institution, index) => {
      const minGrade = 'D+';
      courses.push({
        id: `${programme.replace(/\s+/g, '-').toLowerCase()}-${institution.replace(/\s+/g, '-').toLowerCase()}`,
        name: programme,
        institution,
        type: 'TVET',
        minGrade,
        clusterSubjects: ['English', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'Geography', 'History', 'CRE', 'Agriculture', 'Business Studies'],
        duration: '2 Years',
        description: `KUCCPS certificate programme in ${programme.replace('Certificate in ', '')}`,
        kuccpsLink: 'https://students.kuccps.net/programmes/'
      });
    });
  });

  // Generate Artisan Courses (D+)
  const artisanProgrammes = [
    "Artisan in Electrical Installation", "Artisan in Plumbing", "Artisan in Welding",
    "Artisan in Carpentry", "Artisan in Masonry", "Artisan in Painting", "Artisan in Tiling",
    "Artisan in Automotive Mechanics", "Artisan in Motor Vehicle Technology", "Artisan in Metal Fabrication",
    "Artisan in Tailoring", "Artisan in Dressmaking", "Artisan in Embroidery", "Artisan in Knitting",
    "Artisan in Hairdressing", "Artisan in Beauty Therapy", "Artisan in Nail Technology", "Artisan in Makeup",
    "Artisan in Catering", "Artisan in Food Service", "Artisan in Baking", "Artisan in Pastry",
    "Artisan in Agriculture", "Artisan in Animal Husbandry", "Artisan in Crop Production", "Artisan in Horticulture",
    "Artisan in Leatherwork", "Artisan in Basketry", "Artisan in Pottery", "Artisan in Woodcarving"
  ];

  artisanProgrammes.forEach(programme => {
    tvetInstitutions.slice(0, 15).forEach((institution, index) => {
      const minGrade = 'D+';
      courses.push({
        id: `${programme.replace(/\s+/g, '-').toLowerCase()}-${institution.replace(/\s+/g, '-').toLowerCase()}`,
        name: programme,
        institution,
        type: 'TTC',
        minGrade,
        clusterSubjects: ['English', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'Geography', 'History', 'CRE', 'Agriculture', 'Business Studies'],
        duration: '1 Year',
        description: `KUCCPS artisan programme in ${programme.replace('Artisan in ', '')}`,
        kuccpsLink: 'https://students.kuccps.net/programmes/'
      });
    });
  });

  return courses;
};

export default KUCCPS_CLUSTERS;
